version: "3"
services:
  app:
    build: .
    ports:
      - "1234:1234"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_NAME: empleados
      DB_USER: postgres
      DB_PASSWORD: root
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: empleados
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
